### PR TITLE
Added recommendation for restore points before critical operations an…

### PR DESCRIPTION
**Pull request by janloeffler**
…d another recommendation to use profiling tools to find performance bottlenecks

### CODE REVIEW

**Review by JuergenLeber — APPROVED** [review]
Okay!

**Review by Crixu — COMMENTED** [review]
looks good

**Comment by ataylorme** [comment]
@janloeffler thank you so much for contributing! I would like to suggest a few small tweaks. What do you think of this?

> It is best practice to use performance profiling tools, such as New Relic, AppDynamics or Tideways, to diagnose the performance bottlenecks of your website and infrastructure. These tools will give you insight such as slow performing functions, external HTTP requests, slow database queries and more that are causing poor performance.

**Comment by janloeffler** [comment]
@ataylorme yes, that makes sense, I like your proposal

**Review by ataylorme — APPROVED** [review]

**Comment by ataylorme** [comment]
Thanks @janloeffler - this looks great and has been merged. I'll try to get the hosting handbook updated with these new changes before the next meeting

**Pull request merged**
